LOCAL_PATH:= $(call my-dir)
# NEW Camera For 4.4.3
ifeq ($(STE_CAMERA_JHEAD), true)
include $(CLEAR_VARS)
LOCAL_MODULE := camera.montblanc
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/hw
LOCAL_SRC_FILES := new_pre_built/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
OVERRIDE_BUILT_MODULE_PATH := $(TARGET_OUT_INTERMEDIATE_LIBRARIES)/hw
include $(BUILD_PREBUILT)
else
include $(CLEAR_VARS)
LOCAL_MODULE := camera.montblanc
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/hw
LOCAL_SRC_FILES := pre_built/$(LOCAL_MODULE).so
LOCAL_MODULE_SUFFIX := .so
OVERRIDE_BUILT_MODULE_PATH := $(TARGET_OUT_INTERMEDIATE_LIBRARIES)/hw
include $(BUILD_PREBUILT)
endif

include $(LOCAL_PATH)/ZXImg/Android.mk
